SELECT * FROM [dbo].[TABELA DE CLIENTES]

SELECT ESTADO,  [LIMITE DE CREDITO] FROM [dbo].[TABELA DE CLIENTES]

-- retorna o resultado agrupado por estado e somando o limite de credito
SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO

-- retorna o resultado agrupado por estado e tirando a media do limite de credito
SELECT ESTADO, AVG([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO

-- retorna o resultado agrupado por EMBALAGEM trazendo o maior preco daquela embalagem
SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

-- retorna o resultado agrupado por EMBALAGEM trazendo o menor preco daquela embalagem
SELECT EMBALAGEM, MIN([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

-- retorna o resultado agrupado por EMBALAGEM trazendo o nome do produto
SELECT [NOME DO PRODUTO], EMBALAGEM  FROM [TABELA DE PRODUTOS] ORDER BY EMBALAGEM

-- retorna o resultado agrupado por EMBALAGEM trazendo a quantidade de cada embalagem
SELECT EMBALAGEM, COUNT(*) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

-- retorna por bairro de sp a soma do valor de limite de credito
SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] 
WHERE [ESTADO]  = 'SP' GROUP BY BAIRRO

SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] 
WHERE [ESTADO]  = 'SP' GROUP BY BAIRRO HAVING SUM([LIMITE DE CREDITO]) >= 140000.00 ORDER BY BAIRRO DESC -- APLIQUEI UM HAVING COMO EXEMPLO

SELECT BAIRRO, ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] -- OBRIGATORIAMENTE O VALOR ESPECIFICADO NO SELECT DEVE IR NO GROUP BY
WHERE [ESTADO]  = 'SP' GROUP BY BAIRRO, ESTADO

-- QUERO SOMAR O PRECO DE LISTA DE TODAS AS GARRAFAS
SELECT SUM([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS]

-- QUERO O ESTADO COM MAIOR LIMITE DE CREDITO
SELECT MAX([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES]

--Aproveitando o exercício anterior, quantos itens de venda existem com a maior quantidade de venda para o produto '1101035'?
SELECT COUNT(*) FROM [ITENS NOTAS FISCAIS] WHERE [CODIGO DO PRODUTO] = '1101035' AND QUANTIDADE = 99