

-- RETIRA ESPACO EM BRANCO DO COMECO
SELECT LTRIM('      OLA')


-- RETIRA ESPACO EM BRANCO DO FINAL
SELECT RTRIM('OLA      ')

-- CONCATENA A FRASE
SELECT CONCAT('OLA ','TUDO BEM')
SELECT 'OLA ' + 'TUDO BEM'

-- PEGA AS 7 PRIMEIRAS OPCOES DA DIREITA
SELECT LEFT('RUA AUGUSTA',3) 

-- PEGA AS 3 PRIMEIRAS OPCOES DA ESQUERDA
SELECT RIGHT('RUA AUGUSTA',7) 

-- COLOCA EM CAIXA ALTA
SELECT UPPER('rua augusta')   

-- COLOCA EM CAIXA BAIXA
SELECT LOWER('RUA AUGUSTA')   

-- SUBSTITUI UM DETERMINADO STRING POR OUTRO R. por RUA
SELECT REPLACE('R. AUGUSTA','R.','RUA') 

-- PEGA A POSICAO INICIAL E O NUMERO DE CASAS PRA FRENTE
SELECT SUBSTRING('RUA AUGUSTA', 1, 3) 
SELECT SUBSTRING('RUA AUGUSTA', 2, 4) 

-- DEVOLVE A QUANTIDADE DE CARACTERES
SELECT LEN('RUA AUGUSTA')  

SELECT * FROM [TABELA DE CLIENTES]

SELECT CONCAT(NOME, ' (', CPF, ') ') FROM [TABELA DE CLIENTES]


-- Faça uma consulta que lista o nome do cliente e o endereço completo (com rua, bairro, cidade e estado).
SELECT NOME, CONCAT([ENDERECO 1], ' ', BAIRRO, ' ', CIDADE, ' ', ESTADO) AS ENDERECO_COMPLETO
FROM [TABELA DE CLIENTES]








