
-- RETORNA A HORA DO SISTEMA OPERACIONAL => 2021-12-07 10:00:07.7125412
SELECT SYSDATETIME()

-- RETORNA A HORA DO SISTEMA OPERACIONAL COM A DIFERENCA DO FUSO HORARIO => 2021-12-07 13:19:55.7719188 -03:00
SELECT SYSDATETIMEOFFSET()

-- RETORNA A HORA DO SISTEMA OPERACIONAL COM O FUSO HORARIO
SELECT SYSUTCDATETIME()

-- RETORNA A HORA DO SISTEMA OPERACIONAL => 2021-12-07 10:01:29.117
SELECT CURRENT_TIMESTAMP

-- RETORNA A DATA COM A PRECISAO PARECIDA DO CURRENT_TIMESTAMP => 2021-12-07 10:02:16.090
SELECT GETDATE()

-- RETORNA A DATA COM FUSO HORARIO => 2021-12-07 10:02:16.090
SELECT GETUTCDATE()

-- RETORNA O NOME DO OBJETO COMO NVARCHAR
SELECT DATENAME(YEAR,GETDATE())

-- RETORNA OS MICROSEGUNDOS
SELECT DATENAME(MICROSECOND,GETDATE())

-- RETORNA O MINUTO ATUAL
SELECT DATENAME(MINUTE,GETDATE())

-- RETORNA O NOME DO MES ATUAL
SELECT DATENAME(MONTH,GETDATE())

-- RETORNA O NUMERO DO MES
SELECT DATEPART(MONTH,GETDATE())

-- RETORNA O NUMERO DO DIA
SELECT DAY(GETDATE())

-- RETORNA O NUMERO DO ANO
SELECT YEAR(GETDATE())

-- RETORNA UMA DATA FORMATADA 2015-09-01
SELECT DATEFROMPARTS(2015,9,1)

-- RETORNA O MES DESSA DATA FORMATADA
SELECT DATENAME(MONTH,DATEFROMPARTS(2015,9,1))

-- MONTA UMA DATA + HORARIO MINUTOS E SEGUNDOS 2015-09-01 13:12:11.0120
SELECT DATETIME2FROMPARTS(2015,9,1,13,12,11,120,4)

-- RETORNA A DIFERENCA DE MESES DO DATEFROMPARTS ATE A DATA DE HOJE
SELECT DATEDIFF(MONTH, DATEFROMPARTS(2015,9,1), GETDATE())

-- PEGA A DATA DE HOJE E SOMA +5 MESES
SELECT DATEADD(MONTH, 5, GETDATE())

-- RETORNA 1 TRUE OU 0 FALSE PARA UMA DATA VALIDA OU NAO
SELECT ISDATE('2018-01-01')
SELECT ISDATE('2018-25-28')

SELECT * FROM [NOTAS FISCAIS]

-- RETORNA A DATA ESCRITA POR EXTENSO
SELECT [DATA], CONCAT(DATENAME(DAY, [DATA]), ' ', DATENAME(MONTH, [DATA]), ' ', DATENAME(YEAR, [DATA]))
FROM [NOTAS FISCAIS]


-- Crie uma consulta que mostre o nome e a idade dos clientes.
SELECT [NOME], DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE()) AS IDADE
FROM [TABELA DE CLIENTES]







