

SELECT NOME, BAIRRO FROM [TABELA DE CLIENTES]

-- retorna nome e o bairro que coincide da tabela cliente e vendedores
SELECT NOME, BAIRRO FROM [TABELA DE CLIENTES]
WHERE BAIRRO IN (SELECT BAIRRO FROM [TABELA DE VENDEDORES])



SELECT EMBALAGEM, MAX([PREÇO DE LISTA])
FROM [TABELA DE PRODUTOS]
GROUP BY EMBALAGEM
HAVING MAX([PREÇO DE LISTA]) <= 5

--mesma coisa da consulta acima porem com uma sub query e uma condicional
SELECT NOVA_CONSULTA.EMBALAGEM, NOVA_CONSULTA.MAX_PRECO
FROM (SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS MAX_PRECO FROM
[TABELA DE PRODUTOS] GROUP BY EMBALAGEM)
NOVA_CONSULTA WHERE NOVA_CONSULTA.MAX_PRECO <= 5




-- Qual seria a consulta, usando sub-consulta, que seria equivalente a:
SELECT CPF, COUNT(*) FROM [NOTAS FISCAIS]
WHERE YEAR(DATA) = 2016
GROUP BY CPF
HAVING COUNT(*) > 2000

SELECT NOVA_CONSULTA.CPF, NOVA_CONSULTA.QUANTIDADE FROM
(SELECT CPF, COUNT(*) AS QUANTIDADE FROM [NOTAS FISCAIS] -- É OBRIGATORIO PASSAR UM ALIAS NESSE CASO FOI A QUANTIDADE
WHERE YEAR(DATA) = 2016 GROUP BY CPF)
NOVA_CONSULTA WHERE NOVA_CONSULTA.QUANTIDADE > 2000;