-- A função HAVING, ela é aplicada para que nós possamos fazer um filtro sobre o resultado de um GROUP BY

SELECT * FROM [dbo].[TABELA DE CLIENTES]

SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO

SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO 
HAVING SUM([LIMITE DE CREDITO]) >= 850000

SELECT EMBALAGEM, SUM([PREÇO DE LISTA]) AS VALOR_TOTAL, MAX([PREÇO DE LISTA]) AS VALOR_MAXIMO, MIN([PREÇO DE LISTA]) AS VALOR_MINIMO
FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS PRECO_MAXIMO, MIN([PREÇO DE LISTA]) AS PRECO_MINIMO, SUM([PREÇO DE LISTA]) AS SOMA_PRECO
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM HAVING SUM([PREÇO DE LISTA]) <= 80

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]), MIN([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM HAVING SUM([PREÇO DE LISTA]) <= 80 AND MAX([PREÇO DE LISTA]) >= 6


-- Quais são os clientes que fizeram mais de 2000 compras em 2016?
SELECT CPF, COUNT(*) AS COMPRAS
FROM [NOTAS FISCAIS]
WHERE YEAR(DATA) = 2016
GROUP BY CPF
HAVING COUNT(*) > 2000